### ISSUE TITLE
Difference between `BibParser.parse_entry` and `BibTeX.parse_bibtex`

### ISSUE THREAD

**Issue by vandenman** [Humans-of-Julia/BibParser.jl#30]
Consider the following example
```julia
bib = """
@misc{rstan2019,
    author        = {{Stan Development Team}},
    note          = {R package version 2.19.2},
    year          = {2019},
    url           = {http://mc-stan.org/},
    title         = {{RStan}: the {R} interface to {Stan}}
   }
"""

e1 = BibTeX.parse_bibtex(bib)
e1[2]["rstan2019"]["author"]
# "{ Stan Development Team }" # correct

e2 = BibParser.parse_entry(bib)
e2["rstan2019"].authors
# BibInternal.Name("", "Team}", "", "", "") # incorrect
```
The first entry appears correct, but the second is not. Note that this also propagates to Bibliography.jl.

**Comment by Azzaare** [comment]
Good catch! I need to parse names within braces as a specific case.

I think in the names formatting guide I used to write the parser, only names of people were considered, not the name of other entities.

**Comment by Azzaare** [comment]
Should be fixed by a simple `update` of the julia environment (once the General Registry update).

Let me know, @vandenman , if some other modifications are needed.

**Comment by lgoettgens** [comment]
This issue is actually still present, as there hasn't been a release of `BibInternals.jl` since. Can somebody (maybe @Azzaare) do that?
